# Generated by Django 4.1.3 on 2022-11-06 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='uploads/customers/')),
                ('contact', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restau.contact')),
            ],
        ),
    ]
